FROM node:carbon

# Create app directory

WORKDIR /usr/src/docker-loginapi

# Install app dependencies

# A wildcard is used to ensure both package.json AND package-lock.json are copied

# where available (npm@5+)

COPY package*.json ./

RUN npm install --silent
RUN npm install nodemon --silent
RUN npm install express --silent
RUN npm install mongoose --silent

#To bundle your app’s source code inside the Docker image, use the COPY instruction:

COPY . .

#Your app binds to port 3000 so you’ll use the EXPOSE instruction to have it mapped by the docker daemon:

EXPOSE 5000

CMD [“npm”, “start run”]
CMD [“mongod"]
