version: "2"
services:
  app:
    container_name: nodeapp
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mymongo
    image: mongo:3.0.11
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
  
